name = "Umlaut"
uuid = "92992a2b-8ce5-4a9c-bb9d-58be9a7dc841"
authors = ["Andrei Zhabinski <andrei.zhabinski@gmail.com>"]
version = "0.7.0"

[deps]
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ExprTools = "0.1"
julia = "1.10"
